name: reformly_demo
description: Reformly Flutter Demo

environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  supabase_flutter: ^2.3.4
  app_links: ^6.4.1

flutter:
  uses-material-design: true
